# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('body', models.TextField(verbose_name='正文')),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': '博客',
                'verbose_name': '博客',
            },
        ),
    ]
